name: gh release create
on:
  push:
    branches: "main"
    paths: .github/workflows/gh-release-create.yml
  schedule:
    - cron: "18 */6 * * *"
  workflow_dispatch:
    inputs:
      tag_name: {}
concurrency: ${{ github.workflow }}
jobs:
  gh-release-create:
    runs-on: ubuntu-latest
    steps:
      - id: get-latest-tag
        run: |
          latest_tag=$(gh api repos/typst/typst/releases --jq .[0].tag_name)
          echo "latest-tag=$latest_tag" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          repository: typst/typst
          ref: ${{ steps.get-latest-tag.outputs.latest-tag }}
      - run: cargo install cargo-deb
      - run: cargo deb
      - run: gh release create "$TAG" --generate-notes target/debian/*.deb
        env:
          # Use a PAT so "on: release" gets triggered.
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TAG: ${{ steps.get-latest-tag.outputs.latest-tag }}
