name: Update typst
on:
  push:
    branches: "main"
  schedule:
    - cron: "18 */6 * * *"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  update-typst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          tag=$(gh api repos/typst/typst/releases --jq .[0].tag_name)
          
      - uses: actions4git/add-commit-push@v1
